kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lawliet-k8s-api-server
subjects:
- kind: ServiceAccount
  name: lawliet-k8s-api-server
roleRef:
  kind: Role
  name: lawliet-k8s-api-server
  apiGroup: rbac.authorization.k8s.io
